### ISSUE TITLE
about tinymce for codeigniter quesstion

### ISSUE THREAD

**Issue by kopalam** [matiasperrone/TinyImageManager#1]
Hi,friend.I have some quesstion for your plugins ,how can connect you? example codeigniter version 3.12,tinymce5 version can use? thank you very much

**Comment by matiasperrone** [comment]
Sorry for the long delay, no email from this question.

Basically, if you use the plugin "TinyMCE image manager" sure no issues here.
You do not need the controller, is only as an example.

You need to set the correct method on the routes.php and add the mediaUpload method in the controller of your choice, but be sure to update the route file.

Such plugin has harcoded the route of the script that handles the images,

It was clear enough? please ask again with an example so I maybe more helpful.

Best,
Matias
